-- ============================================================
-- TechBay Seed Data
-- Run this AFTER schema.sql in Supabase SQL Editor
-- ============================================================

INSERT INTO products (slug, name, brand, category, price, original_price, monthly_price, images, colors, storage, specs, description, badges, condition, in_stock, rating, review_count)
VALUES
(
  'iphone-15-pro-max',
  'iPhone 15 Pro Max',
  'Apple',
  'iphones',
  899,
  1199,
  49.95,
  '[{"src": "https://lh3.googleusercontent.com/aida-public/AB6AXuCk9Bei4Lqu4w74QMvzaVQUo8y6G9DYGEX_hps3NfJzGUeucQsO60tTnXSIhmRyKdGpGlKegYm846ZbjQHybmu2W7_mOQ8lr0TI4kT6EnMqGzkDDt-FTclGIcUiSMOHUiBBkaZoO94tJ78G96L8DD_QuVa6y38Ip2Yy7HJnRDb6FrPHYmJmJbPV8BjXYU3J3lcU3bJSJ60TkCG57LEztCaimzFvPewCuC-LRG7S-gZag5Q7FxPfPdvMBiVLKxSBkxpQlZTOcKpPjHs", "alt": "iPhone 15 Pro Max - Natural Titanium"}]',
  '[{"name": "Natural Titanium", "hex": "#948E83"}, {"name": "Blue Titanium", "hex": "#3D4F5F"}, {"name": "White Titanium", "hex": "#F2F1EB"}, {"name": "Black Titanium", "hex": "#3C3B37"}]',
  '[{"label": "256GB", "priceAdd": 0}, {"label": "512GB", "priceAdd": 200}, {"label": "1TB", "priceAdd": 400}]',
  '[{"label": "Display", "value": "6.7\" Super Retina XDR"}, {"label": "Chip", "value": "A17 Pro"}, {"label": "Camera", "value": "48MP Main + 12MP Ultra Wide"}, {"label": "Battery", "value": "Up to 29h video playback"}]',
  'iPhone 15 Pro Max. Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.',
  ARRAY['Titanium Frame', 'A17 Pro Chip'],
  'Certified Refurbished',
  true,
  4.8,
  128
),
(
  'macbook-air-m2',
  'MacBook Air M2',
  'Apple',
  'laptops',
  1099,
  1299,
  NULL,
  '[{"src": "https://lh3.googleusercontent.com/aida-public/AB6AXuBzBIMEODAp1bY9bjpN2yQlGIuEnY36_2Eup_idGpVjwTO4jJiEtvE8VYdn_nc0J5NQ1otKnQJS9mb3JlijjrI-j5G1qSg1sHAh9t7dS4H41rCn5ALCRRNT5y4LMiD3g7okm67FGm4nHPQ5f8PkjnnHzGQ9vVUDvacwXECJSctjs3J7lwThLK2iG8ZdQUDanBFlwz-rNBi-fksm7K15V6iqPZ9DglOpHOOE-xeZFhygDQlOt6TOZ4bKukPUy7NTfAajvKJlBIeFwp0", "alt": "MacBook Air M2 - Silver"}]',
  '[{"name": "Silver", "hex": "#E3E4E5"}, {"name": "Space Gray", "hex": "#7D7E80"}, {"name": "Midnight", "hex": "#2E3642"}, {"name": "Starlight", "hex": "#F0E4D3"}]',
  '[{"label": "256GB", "priceAdd": 0}, {"label": "512GB", "priceAdd": 200}]',
  '[{"label": "Display", "value": "13.6\" Liquid Retina"}, {"label": "Chip", "value": "Apple M2"}, {"label": "Memory", "value": "8GB Unified"}, {"label": "Battery", "value": "Up to 18h"}]',
  'Supercharged by the M2 chip, MacBook Air is strikingly thin, with a silent, fanless design. Gorgeous Liquid Retina display.',
  ARRAY['M2 Chip', 'Fanless Design'],
  'Like New',
  true,
  4.9,
  256
),
(
  'premium-audio-pro',
  'Premium Audio Pro',
  'Sony',
  'audio',
  199,
  349,
  NULL,
  '[{"src": "https://lh3.googleusercontent.com/aida-public/AB6AXuDKtq3FWpQ1pjXeiWXiEx6kamFaYe4LGhrM3-8ojzGEDX4Ycwr8Lhaog2RuyVvxNbv28sqX9xnCRAjm48OJZlH_gsOyjS36fxTi5V3crYwPnycTXJGiWK9T_YE8qn1UnT9sFB_2P0S637eeRVn6upV8oLIAxMwm608SDBkQ4f-ab7LZVaXb2TBX9mJWyaKl4PlvayS4Xdtyo9MIpiY2_MeVeYYorQAJH0SQv0PNxMxDfm1m-CDyxvnkX6PurlHR3ZxAzXpYOia87fk", "alt": "Premium Audio Pro Headphones"}]',
  '[{"name": "Black", "hex": "#1A1A1A"}, {"name": "Silver", "hex": "#C0C0C0"}]',
  NULL,
  '[{"label": "Driver", "value": "40mm"}, {"label": "ANC", "value": "Active Noise Cancellation"}, {"label": "Battery", "value": "30h playback"}, {"label": "Connectivity", "value": "Bluetooth 5.3"}]',
  'Industry-leading noise cancellation with premium sound quality. 30-hour battery life with quick charge.',
  ARRAY['ANC', '30h Battery'],
  'Certified Refurbished',
  true,
  4.7,
  84
),
(
  'galaxy-watch-ultra',
  'Galaxy Watch Ultra',
  'Samsung',
  'watches',
  349,
  649,
  NULL,
  '[{"src": "https://lh3.googleusercontent.com/aida-public/AB6AXuBgzQtyPTYbS3wVha3Ck1tjt0hKq9MAVAEkAlt0UlDPowC9h4XdFUeBoHiTgG6fpqQfgnsFFpv5Bz2THPQD5i9AXAKCYKdnnD8kZr8SzijjtTlw01gE5Ibu5jfl4beVjz1JyXvEhXLn0cuhhMB1dYgJcECDhDfzc8gE2AIKDk5FE-4nltdlwcGQdQM_d69q3MW3Xq17-ymtN0G1ztbnGDPYbLpNQ5QCq0RIfj9rwZELnE_SxaI1quPg0s4OSdKfK8zJOlIuEsCDAkU", "alt": "Galaxy Watch Ultra"}]',
  '[{"name": "Titanium Gray", "hex": "#7A7A7A"}, {"name": "Titanium Silver", "hex": "#C4C4C4"}]',
  NULL,
  '[{"label": "Display", "value": "1.5\" Super AMOLED"}, {"label": "Battery", "value": "590mAh"}, {"label": "Water Resistance", "value": "10ATM"}, {"label": "OS", "value": "Wear OS 5"}]',
  'The ultimate outdoor smartwatch. Built tough with titanium grade, 10ATM water resistance.',
  ARRAY['Titanium', '10ATM'],
  'Like New',
  true,
  4.9,
  312
),
(
  'ipad-pro-12-9',
  'iPad Pro 12.9"',
  'Apple',
  'tablets',
  1099,
  1299,
  NULL,
  '[{"src": "https://lh3.googleusercontent.com/aida-public/AB6AXuCjWuD-UMSx2Qzy8mdfXVGG6ziIJNkmkNZJBAAunmArjjprr8ZJKY0an_kI0lrRsjUKaeVeP8G9bGtZt6r4qGSdhPEMpVQPxpS4bZouMSHeHtcP-7qNTMX7JNvoim5cL7zZSdzoVGA6M0xlSuCZXj5DbTN6QLWyuxqpIiAIdXGh_QuUR8ipQ_v3-SK0zPKN_JLMSkBH5zAfw9AWNrdFWBLMpPruaNE4xnw_DYKrBJDu5v0siOIEArU6E1unsVO0sw8rL1OfA8lJriQ", "alt": "iPad Pro 12.9 inch"}]',
  '[{"name": "Space Gray", "hex": "#68696D"}, {"name": "Silver", "hex": "#E3E4E5"}]',
  '[{"label": "128GB", "priceAdd": 0}, {"label": "256GB", "priceAdd": 100}, {"label": "512GB", "priceAdd": 200}]',
  '[{"label": "Display", "value": "12.9\" Liquid Retina XDR"}, {"label": "Chip", "value": "Apple M2"}, {"label": "Camera", "value": "12MP Wide + 10MP Ultra Wide"}, {"label": "Connectivity", "value": "Wi-Fi 6E"}]',
  'The ultimate iPad experience. Stunning Liquid Retina XDR display, M2 chip, superfast wireless.',
  ARRAY['M2 Chip', 'XDR Display'],
  'Certified Refurbished',
  true,
  4.8,
  195
),
(
  'samsung-galaxy-s25-ultra',
  'Samsung Galaxy S25 Ultra',
  'Samsung',
  'samsung',
  999,
  1299,
  NULL,
  '[{"src": "https://lh3.googleusercontent.com/aida-public/AB6AXuAQGH6_84dRuU18M2b4EUObkVgwoxbqvSsO-L4m3aJU2M8LjnhM0rcEk9G3aQb3Su9OyiBLyGSRJd9IggYczDAl0tveuOw9w89AtEHs06TxCmkvVH-RZk8yoLzw4sDy0ia3O3y7mi2BmLHsx42iTp2-fSnQ_WsDWh4KTUUOypT2TRBL2D9K6DUx0e2ssMESjNSc3_89EO4KSu26052VLUIEEm8m20vtBTeP6zHTw_tTbSkFg-bn4pjKXR8K-8yChRI-7RBD8lRetqc", "alt": "Samsung Galaxy S25 Ultra"}]',
  '[{"name": "Titanium Gray", "hex": "#848789"}, {"name": "Titanium Black", "hex": "#2B2B2B"}, {"name": "Titanium Blue", "hex": "#B0C4DB"}]',
  '[{"label": "256GB", "priceAdd": 0}, {"label": "512GB", "priceAdd": 120}, {"label": "1TB", "priceAdd": 240}]',
  '[{"label": "Display", "value": "6.8\" Dynamic AMOLED 2X"}, {"label": "Chip", "value": "Snapdragon 8 Elite"}, {"label": "Camera", "value": "200MP Main"}, {"label": "Battery", "value": "5000mAh"}]',
  'The most powerful Galaxy ever. With Galaxy AI built in and a 200MP camera.',
  ARRAY['Galaxy AI', 'S Pen'],
  'New',
  true,
  4.8,
  167
);
